config/routes.rb
Rails.application.routes.draw do
  resources :tacos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/taco.rb
class Taco < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tacos_controller.rb
class TacosController < ApplicationController
  before_action :set_taco, only: [:show, :edit, :update, :destroy]

  # GET /tacos
  # GET /tacos.json
  def index
    @tacos = Taco.all
    render :json => @tacos
  end

  # GET /tacos/1
  # GET /tacos/1.json
  def show
  end

  # GET /tacos/new
  def new
    @taco = Taco.new
  end

  # GET /tacos/1/edit
  def edit
  end

  # POST /tacos
  # POST /tacos.json
  def create
    @taco = Taco.new(taco_params)

    respond_to do |format|
      if @taco.save
        format.html { redirect_to @taco, notice: 'Taco was successfully created.' }
        format.json { render :show, status: :created, location: @taco }
      else
        format.html { render :new }
        format.json { render json: @taco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tacos/1
  # PATCH/PUT /tacos/1.json
  def update
    respond_to do |format|
      if @taco.update(taco_params)
        format.html { redirect_to @taco, notice: 'Taco was successfully updated.' }
        format.json { render :show, status: :ok, location: @taco }
      else
        format.html { render :edit }
        format.json { render json: @taco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tacos/1
  # DELETE /tacos/1.json
  def destroy
    @taco.destroy
    render :json => @taco.id, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taco
      @taco = Taco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taco_params
      params.require(:taco).permit(:meat, :rice, :salsa, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tacos_helper.rb
module TacosHelper
end

app/views/layouts/application.html.haml
!!!
%html{"ng-app" => "app"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LD Studios Rails Interview
    = csrf_meta_tags
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css", :media => "screen", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css", :media => "screen", :rel => "stylesheet", :type => "text/css"}/
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js", :type => "text/javascript"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js", :type => "text/javascript"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js", :type => "text/javascript"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.min.js", :type => "text/javascript"}
  %body{"ng-cloak" => ""}
    %article.container.tacos{"ng-controller" => "TacosCtrl as tc"}
      %h1 LD Taco Shop
      .alert.alert-danger{"ng-if" => "tc.listError"}
        %strong Error getting tacos:
        {{tc.listError}}
      .alert.alert-danger{"ng-if" => "tc.createError"}
        %strong Error ordering taco:
        {{tc.createError}}
      .alert.alert-danger{"ng-if" => "tc.deleteError"}
        %strong Error deleting taco:
        {{tc.deleteError}}
      %h3 Order a new Taco
      %form{:name => "form", "ng-submit" => "form.$valid && tc.createTaco()", :novalidate => "", :role => "form"}
        %fieldset{"ng-disabled" => "tc.creatingTaco"}
          %label Meat
          .form-group
            %label.radio-inline
              %input{:name => "meat", "ng-model" => "tc.newTaco.meat", :type => "radio", :value => "chicken"}/
              Chicken
            %label.radio-inline
              %input{:name => "meat", "ng-model" => "tc.newTaco.meat", :type => "radio", :value => "steak"}/
              Steak
          %label Sides
          .form-group
            %label.checkbox-inline
              %input{"ng-model" => "tc.newTaco.rice", :type => "checkbox"}/
              Rice
            %label.checkbox-inline
              %input{"ng-model" => "tc.newTaco.salsa", :type => "checkbox"}/
              Salsa
          %label Notes
          .form-group
            %textarea.form-control{"ng-model" => "tc.newTaco.notes", :rows => "3"}
          %button.btn.btn-primary{:type => "submit"} {{tc.creatingTaco ? 'Ordering Taco...' : 'Order Taco'}}
      %h3 Taco Queue
      %p{"ng-if" => "!tc.tacos.length"} Empty! Order some tacos!
      %table.table.table-striped.tacos{"ng-if" => "tc.tacos.length"}
        %thead
          %tr
            %th Order #
            %th Meat
            %th Rice
            %th Salsa
            %th Notes
            %th
        %tbody
          %tr{"ng-repeat" => "taco in tc.tacos track by taco.id"}
            %td {{taco.id}}
            %td.meat {{taco.meat}}
            %td.rice {{taco.rice ? 'yes' : 'no'}}
            %td.salsa {{taco.salsa ? 'yes' : 'no'}}
            %td {{taco.notes}}
            %td
              %button.btn.btn-danger.btn-xs.fa.fa-times{"ng-click" => "tc.deleteTaco(taco)", :title => "Delete this Taco", :type => "button"}
    :css
      article.tacos form {
        background: #eee;
        padding: 10px;
        border-radius: 5px;
      }

      table.tacos td.meat,
      table.tacos td.rice,
      table.tacos td.salsa {
        text-transform: capitalize;
      }
    :javascript
      var app = window.app = angular.module('app', []);

      app.service('TacoService', function($http) {
        function fromJSON(json) {
          var taco = _.omit(json, '_id');
          taco.id = json.id || json._id;
          return taco;
        }

        this.getTacos = function() {
          return $http.get('/tacos').then(function(result) {
            return _.map(result.data, fromJSON);
          });
        };

        this.createTaco = function(json) {
          return $http({
            method: 'POST',
            url: '/tacos',
            data: json
          }).then(function(result) {
            return fromJSON(result.data);
          });
        };

        this.deleteTaco = function(id) {
          return $http({
            method: 'DELETE',
            url: '/tacos/' + id
          });
        };
      });

      app.controller('TacosCtrl', function(TacoService) {
        var tc = this;

        // Load the list of tacos we already have
        TacoService.getTacos().then(function(tacos) {
          tc.tacos = tacos;
        }).catch(function(err) {
          tc.listError = err.message || err.statusText;
        });

        // Create a default taco for new tacos
        var defaultTaco = {
          meat: 'chicken',
          rice: false,
          salsa: false,
          notes: ''
        };
        tc.newTaco = _.clone(defaultTaco);

        tc.createTaco = function() {
          tc.createError = null;
          tc.creatingTaco = true;
          TacoService.createTaco(tc.newTaco).then(function(taco) {
            tc.tacos.push(taco);
            tc.newTaco = _.clone(defaultTaco);
          }).catch(function(err) {
            tc.createError = err.message || err.statusText;
          }).finally(function() {
            tc.creatingTaco = false;
          })
        };

        tc.deleteTaco = function(taco) {
          tc.deleteError = null;
          TacoService.deleteTaco(taco.id).then(function() {
            var index = _.indexOf(tc.tacos, taco);
            tc.tacos.splice(index, 1);
          }).catch(function(err) {
            tc.deleteError = err.message || err.statusText;
          });
        };
      });

app/views/layouts/blank.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsCodingQuiz
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/pages/home.html.haml
%h1 Home

app/views/tacos/_form.html.erb
<%= form_for(taco) do |f| %>
  <% if taco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(taco.errors.count, "error") %> prohibited this taco from being saved:</h2>

      <ul>
      <% taco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meat %>
    <%= f.text_field :meat %>
  </div>

  <div class="field">
    <%= f.label :rice %>
    <%= f.text_field :rice %>
  </div>

  <div class="field">
    <%= f.label :salsa %>
    <%= f.text_field :salsa %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tacos/edit.html.erb
<h1>Editing Taco</h1>

<%= render 'form', taco: @taco %>

<%= link_to 'Show', @taco %> |
<%= link_to 'Back', tacos_path %>

app/views/tacos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tacos</h1>

<table>
  <thead>
    <tr>
      <th>Meat</th>
      <th>Rice</th>
      <th>Salsa</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tacos.each do |taco| %>
      <tr>
        <td><%= taco.meat %></td>
        <td><%= taco.rice %></td>
        <td><%= taco.salsa %></td>
        <td><%= taco.notes %></td>
        <td><%= link_to 'Show', taco %></td>
        <td><%= link_to 'Edit', edit_taco_path(taco) %></td>
        <td><%= link_to 'Destroy', taco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taco', new_taco_path %>

app/views/tacos/new.html.erb
<h1>New Taco</h1>

<%= render 'form', taco: @taco %>

<%= link_to 'Back', tacos_path %>

app/views/tacos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meat:</strong>
  <%= @taco.meat %>
</p>

<p>
  <strong>Rice:</strong>
  <%= @taco.rice %>
</p>

<p>
  <strong>Salsa:</strong>
  <%= @taco.salsa %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @taco.notes %>
</p>

<%= link_to 'Edit', edit_taco_path(@taco) %> |
<%= link_to 'Back', tacos_path %>